# Generated by Django 3.1.3 on 2020-11-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
